# Generated by Django 4.1.3 on 2022-11-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.FloatField(default=0.0),
        ),
    ]
