# Generated by Django 4.1.3 on 2022-11-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productvariant_price_productvariant_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
