# Generated by Django 4.1.3 on 2022-11-11 16:37

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productvariant_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='file_path',
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=product.models.photo_upload_path),
        ),
    ]
